title: Mozilla Perú
description: Entusiastas de tecnologías web, defensores y promotores de la web abierta
url: https://mozilla.pe
collections:
  about_us:
    output: true
    permalink: /nosotros/:slug
  webdev_survey:
    output: true
    permalink: /estudioweb/:name
  devtools_tips:
    output: true
    permalink: /devtools-tips/:slug
plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
