title: Mozilla Perú
description: Entusiastas de tecnologías web, defensores y promotores de la web abierta
url: https://www.mozilla.pe
collections:
  about_us:
    output: true
    permalink: /nosotros/:slug
  webdev_survey:
    output: true
    permalink: /estudioweb/:name
